### PR TITLE
Unused result from write() fails compilation on Ubuntu 16.04 container

### PR DESCRIPTION
**Pull request by JPablomr**
I was trying to build this using the `ubuntu:16.04` container and ran into this error.
There probably is a better way to to this.

### CODE REVIEW

**Comment by droundy** [comment]
This is causing trouble because warnings are treated as errors? It's possible the answer is to change that rather than changing the code in, as you say, a rather ugly way. We ignore the output because there is nothing useful we could do with it...

**Comment by droundy** [comment]
Could you share more about your build situation?

**Comment by JPablomr** [comment]
Sure,
At the moment this bigbro is getting pulled via [fac](https://github.com/droundy/fac/blob/master/build/linux.sh)

It's a pretty standard Docker container:
```
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install curl && \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install --no-install-recommends \
        build-essential \
        git \
        language-pack-en \
        libevent-dev \
        liblzo2-dev \
        libmysqlclient-dev \
        libpopt-dev \
        liboboe-dev \
        python \
        python-dev \
        python-pip \
        python-virtualenv \
        python-setuptools \
        python-wheel \
        python3 \
        pkg-config \
        vim \
        virtualenv

**Comment by droundy** [comment]
I think I've addressed this issue with (I forgot which) commit.

**Pull request closed without merging**
